#!/usr/bin/env perl
use 5.016;
use warnings;
use FindBin qw($RealBin $Bin $Script);

sub is_mingw() {
    if (exists $ENV{'MSYSTEM'}) {
        if (($ENV{'MSYSTEM'} eq 'MINGW64')
            or ($ENV{'MSYSTEM'} eq 'MINGW32')
            or ($ENV{'MSYSTEM'} eq 'MSYS')) {
            return 1;
        }
    }
    return 0;
}

sub file_get_contents {
    my $filename = shift;
    my $result = '';
    if (open(my $fh, '<:encoding(UTF-8)', $filename)) {
        while (my $line = <$fh>) {
            $result .= $line;
        }
    }
    return $result;
}

sub file_put_contents {
    my $filename = shift;
    my $content = shift;
    if (open(my $fh, '>:encoding(UTF-8)', $filename)) {
        print $fh $content;
        close $fh;
        return 1;
    }
    return 0;
}

sub action_self_install {
    if (is_mingw()) {
        my $fname = $ENV{'HOME'} . '/.bash_profile';
        my $initPath = 'PATH=$PATH:$HOME/bin/6umpukc';
        if (-f $fname) {
            my $content = file_get_contents($fname);
            if (index($content, $initPath) < 0) {
                file_put_contents($fname, $content . "\n" . $initPath . "\n");
            }
        }
        else {
            file_put_contents($fname, "\n" . $initPath . "\n");
        }
        return;
    }
    my $homeBin = $ENV{'HOME'} . '/bin';
    if (-d $homeBin) {
        my $homeScript = $homeBin . '/' . $Script;
        if (-l $homeScript) {
            unlink($homeScript);
        }
        symlink($Bin . '/' . $Script, $homeScript);
    }
    else {
        die('$HOME/bin/ not exists');
    }
}

action_self_install();
